# Generated by Django 4.2 on 2023-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_description',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
