# Generated by Django 4.2 on 2023-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_project_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
