# Generated by Django 4.2 on 2023-05-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_intto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='intto',
            new_name='intro',
        ),
    ]
