# Generated by Django 4.2 on 2023-05-15 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_intto_project_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('email_link', models.URLField(blank=True)),
                ('title_description', models.TextField(blank=True, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('quarter', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('cv_link', models.URLField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_profile', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
            ],
        ),
    ]
